### PR TITLE
Adding LandWorker method

### PR DESCRIPTION
**Pull request by arwineap**
This adds landworker to the go-concourse api

This change is required to get land-worker into fly

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@arwineap Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/go-concourse&pullRequestId=7)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/go-concourse&pullRequestId=7) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@arwineap Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/go-concourse&pullRequestId=7)!

**Comment by chendrix** [comment]
needed-by concourse/fly#173

**Comment by topherbullock** [comment]
Closing since concourse/fly#173 was closed.

**Pull request closed without merging**
